---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fakenames-db
  namespace: demo
  description: Cockroach database populated from https://fakenames.org dataset
spec:
  type: database
  owner: testructer
  system: fastapi-demo
  tags:
    - postgres
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fakenames
  description: Fake identity provider
  tags:
    - rest
    - fastapi
    - python3
  # annotations:
  #   # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
  #   backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: testructer
  system: fastapi-demo
  definition:
    $text: https://github.com/testruction/fastapi-sqlalchemy-cockroachdb/blob/main/specs/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  namespace: demo
  description: FastApi backend API demonstration
  tags:
    - fastapi
    - dash
    - python3
    - ui
  annotations:
    argocd/app-name: demo
    prometheus.io/alert: >-
      demo-fastapi-backendHighErrorRate
    prometheus.io/rule: >-
      slo:sli_error:ratio_rate5m{sloth_service="demo-fastapi-backend"}
    backstage.io/kubernetes-id: backend
    backstage.io/kubernetes-namespace: fastapi-demo
  links:
    - url: http://localhost/v1/docs
      title: Api documentation
      icon: docs
      type: apidocs
spec:
  type: service
  lifecycle: production
  owner: testructer
  system: fastapi-demo
  dependsOn:
    - resource:fakenames-db
  providesApis:
    - api:fakenames
