---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: demo
  description: FastApi and Dash frontend demonstration
  tags:
    - fastapi
    - dash
    - python3
    - ui
  annotations:
    argocd/app-name: demo
    prometheus.io/alert: >-
      demo-fastapi-frontendHighErrorRate
    prometheus.io/rule: >-
      slo:sli_error:ratio_rate5m{sloth_service="demo-fastapi-frontend"}
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/component=frontend'
  links:
    - url: http://localhost
      title: Home page
      icon: home
      type: admin-dashboard
    - url: https://metrics.example-org.com
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://logs.example-org.com
      title: logs
      icon: assignment
      type: logs-dashboard
spec:
  type: service
  lifecycle: production
  owner: testructer
  system: fastapi-demo
  consumesApis:
    - api:fakenames
  dependsOn:
    - component:backend
